### ISSUE TITLE
"Inner" Vs Hyper parameters

### ISSUE THREAD

**Issue by echo66** [LDSSA/data_science_101_tutorial#1]
In learning unit 2, the author mentions "hyper parameters" but doesn't give any hints on: 
- what are hyper parameters;
- how are they different from the "inner" parameters (e.g.: cuts of a tree, weights of a linear regression, weights of a neural network).

If these are notebooks with the basic stuff, maybe a better explanation of these terms is required.

**Comment by PedroGFonseca** [comment]
Closing as it's been open for a couple of years and this repo is pretty obsolete
